#!/bin/bash

current_path=$(cd $(dirname $0);pwd)
echo current_path=$current_path

pid=$(ps -ef | grep $current_path/ | grep java | awk '{print $2}')
echo start to kill processid:$pid

kill -9 $pid
echo kill processid succ ..

echo "rm -rf webapps/*"
rm -rf ./webapps/*

echo "rm -rf logs/*"
rm -rf ./logs/*

echo "exec ossdownload"
#python /home/serving/bin/oss/oss_builder.py -e cm8 -t download $1 webapps/
python ~/.oss/oss_builder.py -t download $1 webapps/

echo "startup server .."
./bin/startup.sh

logFile=logs/billing-task.log
exist=0
while [ $exist -ne 1 ]
  do
    if [ -f $logFile ]; then
      echo "$logFile has generated by server .."
      exist=1
    else 
      echo "$logFile does not generate by server until now , sleep 2s.."
      sleep 2s
    fi
  done

tail -f $logFile -n 5000
